defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/PiWeb-Api"
images:
  ok: "![Ok](/PiWeb-Api/images/ok.png)"
  warning: "![Warning](/PiWeb-Api/images/warning.png)"
  info: "![Info](/PiWeb-Api/images/info.png)"
  generalInformation16: "![DatabaseInfo](/PiWeb-Api/images/database-info.png)"
  generalInformation40: "![DatabaseInfo](/PiWeb-Api/images/database-info40.png)"
  dataservice40: "![DatabaseTable](/PiWeb-Api/images/database-table40.png)"
  rawdataservice40: "![DatabaseAttach](/PiWeb-Api/images/database-attach40.png)"
  dataservice16: "![DatabaseTable](/PiWeb-Api/images/database-table.png)"
  rawdataservice16: "![DatabaseAttach](/PiWeb-Api/images/database-attach.png)"
sections:
  getLabel: <span class="label label-primary">Get</span>
  postLabel: <span class="label label-success">Post</span>
  putLabel: <span class="label label-warning">Put</span>
  deleteLabel: <span class="label label-danger">Delete</span>
headers:
  example: "##### ![Example](/PiWeb-Api/images/document-info.png) Example: "
  bestPractice: "#### ![Best practice](/PiWeb-Api/images/footsteps.png) Best practice: "
  request: "##### Request"
  response: "##### Response"
gems:
  - jekyll-redirect-from
